# Builder stage 
FROM python:3.12-slim AS builder

WORKDIR /app

# build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# venv stage 
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Runner another stage 
FROM python:3.12-slim

WORKDIR /app

# runtime libs
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy venv
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
ENV PYTHONPATH=/app

# shared code
COPY shared/ shared/

# Copy auth service code
COPY auth_service/ auth_service/

#cmd run 1 command 
CMD ["uvicorn", "auth_service.app.main:app", "--host", "0.0.0.0", "--port", "8001", "--root-path", "/auth"]