def advance_analytics_1_month():
    return{"Total Revenue": "$4.8K",
        "Ocupancy Rate": "83%",
        "Collection Rate": "6.8%",
        "Maintenance Efficiency": "97.2%",
        "Energy Cost": "$12.8K",
        "Tenant Satisfaction": "4.3/5"}
def advance_analytics_7_days():
    return{"Total Revenue": "$1.2K",
        "Ocupancy Rate": "82.5%",
        "Collection Rate": "98.1%",
        "Maintenance Efficiency": "96.5%",
        "Energy Cost": "$3.2K",
        "Tenant Satisfaction": "4.2/5"}
def advance_analytics_3_month():
    return{"Total Revenue": "$714.8K",
        "Ocupancy Rate": "83.4%",
        "Collection Rate": "96.8%",
        "Maintenance Efficiency": "97.2%",
        "Energy Cost": "$212.8K",
        "Tenant Satisfaction": "4.3/5"}

def advance_analytics_6_month():
    return{"Total Revenue": "$714.8K",
        "Ocupancy Rate": "83.4%",
        "Collection Rate": "96.8%",
        "Maintenance Efficiency": "97.2%",
        "Energy Cost": "$212.8K",
        "Tenant Satisfaction": "4.3/5"}

def advance_analytics_12_month():
    return{"Total Revenue": "$714.8K",
        "Ocupancy Rate": "83.4%",
        "Collection Rate": "96.8%",
        "Maintenance Efficiency": "97.2%",
        "Energy Cost": "$212.8K",
        "Tenant Satisfaction": "4.3/5"}

def revenue_analytics():
    return [
        {"month": "January",
            "trends": {"total_revenue": 120000,
                "rental_income": 80000,
                "other_income": 40000}},
        {"month": "February",
            "trends": {"total_revenue": 100000,
                "rental_income": 70000,
                "other_income": 30000}},
        {"month": "March",
            "trends": {"total_revenue": 110000,
                "rental_income": 75000,
                "other_income": 35000}},
        {"month": "April",
            "trends": {"total_revenue": 115000,
                "rental_income": 78000,
                "other_income": 37000}},
        {"month": "May",
            "trends": {"total_revenue": 125000,
                "rental_income": 85000,
                "other_income": 40000}},
        {"month": "June",
            "trends": {"total_revenue": 130000,
                "rental_income": 88000,
                "other_income": 42000}},
        {"month": "July",
            "trends": {"total_revenue": 128000,
                "rental_income": 86000,
                "other_income": 42000}},
        {"month": "August",
            "trends": {"total_revenue": 135000,
                "rental_income": 90000,
                "other_income": 45000}},
        {"month": "September",
            "trends": {"total_revenue": 140000,
                "rental_income": 93000,
                "other_income": 47000}},
        {"month": "October",
            "trends": {"total_revenue": 145000,
                "rental_income": 96000,
                "other_income": 49000}},
        {"month": "November",
            "trends": {"total_revenue": 150000,
                "rental_income": 100000,
                "other_income": 50000}},
        {"month": "December",
            "trends": {"total_revenue": 160000,
                "rental_income": 105000,
                "other_income": 55000}}]
def site_profitability():
    return [{"month": "January",
            "profitability": {"site_a": 55000,
                "site_b": 42000,
                "site_c": 23000,
                "total_profit": 120000}},
        {"month": "February",
            "profitability": {"site_a": 50000,
                "site_b": 38000,
                "site_c": 22000,
                "total_profit": 110000}},
        {"month": "March",
            "profitability": {"site_a": 52000,
                "site_b": 40000,
                "site_c": 24000,
                "total_profit": 116000}},
        {"month": "April",
            "profitability": {"site_a": 56000,
                "site_b": 42000,
                "site_c": 25000,
                "total_profit": 123000}},
        {"month": "May",
            "profitability": {"site_a": 60000,
                "site_b": 45000,
                "site_c": 26000,
                "total_profit": 131000}},
        {"month": "June",
            "profitability": {"site_a": 61000,
                "site_b": 46000,
                "site_c": 27000,
                "total_profit": 134000}},
        {"month": "July",
            "profitability": {"site_a": 62000,
                "site_b": 47000,
                "site_c": 28000,
                "total_profit": 137000}},
        {"month": "August",
            "profitability": {"site_a": 65000,
                "site_b": 49000,
                "site_c": 29000,
                "total_profit": 143000}},
        {"month": "September",
            "profitability": {"site_a": 67000,
                "site_b": 50000,
                "site_c": 30000,
                "total_profit": 147000}},
        {"month": "October",
            "profitability": {"site_a": 69000,
                "site_b": 52000,
                "site_c": 31000,
                "total_profit": 152000}},
        {"month": "November",
            "profitability": {"site_a": 71000,
                "site_b": 54000,
                "site_c": 33000,
                "total_profit": 158000}},
        {"month": "December",
            "profitability": {"site_a": 75000,
                "site_b": 56000,
                "site_c": 35000,
                "total_profit": 166000}}]
def collection_performance():
    return [{"month": "January",
            "collection": {"billed_amount": 150000,
                "collected_amount": 145000,
                "collection_rate": "96.7%"}},
        {"month": "February",
            "collection": {"billed_amount": 148000,
                "collected_amount": 142000,
                "collection_rate": "95.9%"}},
        {"month": "March",
            "collection": {"billed_amount": 152000,
                "collected_amount": 147000,
                "collection_rate": "96.7%"}},
        {"month": "April",
            "collection": {"billed_amount": 160000,
                "collected_amount": 154000,
                "collection_rate": "96.2%"}},
        {"month": "May",
            "collection": {"billed_amount": 162000,
                "collected_amount": 157000,
                "collection_rate": "96.9%"}},
        {"month": "June",
            "collection": {"billed_amount": 165000,
                "collected_amount": 159000,
                "collection_rate": "96.4%"}},
        {"month": "July",
            "collection": {"billed_amount": 170000,
                "collected_amount": 165000,
                "collection_rate": "97.1%"}},
        {"month": "August",
            "collection": {"billed_amount": 172000,
                "collected_amount": 166000,
                "collection_rate": "96.5%"}},
        {"month": "September",
            "collection": {"billed_amount": 175000,
                "collected_amount": 169000,
                "collection_rate": "96.6%"}},
        {"month": "October",
            "collection": {"billed_amount": 178000,
                "collected_amount": 172000,
                "collection_rate": "96.6%"}},
        {"month": "November",
            "collection": {"billed_amount": 180000,
                "collected_amount": 174000,
                "collection_rate": "96.7%"}},
        {"month": "December",
            "collection": {"billed_amount": 185000,
                "collected_amount": 179000,
                "collection_rate": "96.8%"}}]
def occupancy_trends():
    return [{"month": "January",
            "occupancy": {"occupied": 415,
                "available": 70,
                "maintenance": 15,}},
        {"month": "February",
            "occupancy": {"occupied": 420,
                "available": 65,
                "maintenance": 15,}},
        {"month": "March",
            "occupancy": {"occupied": 425,
                "available": 60,
                "maintenance": 15,}},
        {"month": "April",
            "occupancy": {"occupied": 418,
                "available": 67,
                "maintenance": 15,}},
        {"month": "May",
            "occupancy": {"occupied": 430,
                "available": 55,
                "maintenance": 15,}},
        {"month": "June",
            "occupancy": {"occupied": 435,
                "available": 50,
                "maintenance": 15,}},
        {"month": "July",
            "occupancy": {"occupied": 440,
                "available": 45,
                "maintenance": 15,}},
        {"month": "August",
            "occupancy": {"occupied": 445,
                "available": 40,
                "maintenance": 15,}},
        {"month": "September",
            "occupancy": {"occupied": 442,
                "available": 43,
                "maintenance": 15,}},
        {"month": "October",
            "occupancy": {"occupied": 448,
                "available": 37,
                "maintenance": 15,}},
        {"month": "November",
            "occupancy": {"occupied": 450,
                "available": 35,
                "maintenance": 15}},
        {"month": "December",
            "occupancy": {"occupied": 455,
                "available": 30,
                "maintenance": 15,}}]
def space_type_performance():
    return [{"month": "January",
            "spaces": {"parking": 120,
                "hotel_rooms": 80,
                "offices": 60,
                "shops": 45,
                "apartments": 200}},
        {"month": "February",
            "spaces": {"parking": 125,
                "hotel_rooms": 78,
                "offices": 62,
                "shops": 47,
                "apartments": 205}},
        {"month": "March",
            "spaces": {"parking": 130,
                "hotel_rooms": 82,
                "offices": 65,
                "shops": 50,
                "apartments": 210}},
        {"month": "April",
            "spaces": {"parking": 128,
                "hotel_rooms": 84,
                "offices": 63,
                "shops": 48,
                "apartments": 212}},
        {"month": "May",
            "spaces": {"parking": 132,
                "hotel_rooms": 85,
                "offices": 67,
                "shops": 52,
                "apartments": 218}},
        {"month": "June",
            "spaces": {"parking": 135,
                "hotel_rooms": 88,
                "offices": 70,
                "shops": 55,
                "apartments": 220}},
        {"month": "July",
            "spaces": {"parking": 138,
                "hotel_rooms": 90,
                "offices": 72,
                "shops": 56,
                "apartments": 225}},
        {"month": "August",
            "spaces": {"parking": 140,
                "hotel_rooms": 92,
                "offices": 74,
                "shops": 58,
                "apartments": 228}},
        {"month": "September",
            "spaces": {"parking": 142,
                "hotel_rooms": 95,
                "offices": 75,
                "shops": 60,
                "apartments": 230}},
        {"month": "October",
            "spaces": {"parking": 145,
                "hotel_rooms": 97,
                "offices": 77,
                "shops": 62,
                "apartments": 233}},
        {"month": "November",
            "spaces": {"parking": 148,
                "hotel_rooms": 100,
                "offices": 80,
                "shops": 65,
                "apartments": 240}},
        {"month": "December",
            "spaces": {"parking": 150,
                "hotel_rooms": 102,
                "offices": 82,
                "shops": 67,
                "apartments": 245}}]
def portfolio_distribution():
    return {"distribution": {"parking": 120,
            "hotel_rooms": 80,
            "offices": 60,
            "shops": 40,
            "apartments": 200},
        "percentages": {"parking": "20%",
            "hotel_rooms": "13.3%",
            "offices": "10%",
            "shops": "6.7%",
            "apartments": "50%"},
        "total_units": 500}

def yoy_performance():
    return{"Revenue" : "$715 K",
        "Occupancy" : "83.4%",
        "Expenses" : "$429 K",
        "Profit" : "$286 K"}

def site_comparision():
    return[{"Site" : "Grand Plaza",
        "Occupancy" : "89.2%",
        "Revenue" : "$285 K",
        "Rating" : "4.5/5",
        "Efficiency" : "97.5%",},
        {"Site": "Tech Park",
        "Occupancy" : "85.7%",
        "Revenue" : "$245 K",
        "Rating" : "4.2/5",
        "Efficiency" : "91.8%",},
        {"Site": "Luxury Hotel",
        "Occupancy" : "78.3%",
        "Revenue" : "$185 K",
        "Rating" : "4.7/5",
        "Efficiency" : "96.3%",}]
    
def maintenance_efficiency():
    return [{"Month" : "2024-01",
            "Completed" : 45 ,
            "Pending" : 12 ,
            "Overdue": 3,
            "Efficiency": "88.5%"},
        {"Month" : "2024-02",
            "Completed" : 52,
            "Pending" : 8,
            "Overdue": 2,
            "Efficiency": "92.1%"},
        {"Month" : "2024-03",
            "Completed" : 48 ,
            "Pending" : 10,
            "Overdue": 1,
            "Efficiency" : "89.7%"},
        {"Month" : "2024-04",
            "Completed" : 55,
            "Pending" : 6,
            "Overdue": 2,
            "Efficiency" : "94.2%"},
        {"Month" : "2024-05",
            "Completed" : 61,
            "Pending" : 9,
            "Overdue": 1,
            "Efficiency" : "91.8%"},
        {"Month" : "2024-06",
            "Completed" : 58,
            "Pending" : 7,
            "Overdue": 0,
            "Efficiency" : "96.3%"},
        {"Month" : "2024-07",
            "Completed" : 63,
            "Pending" : 5,
            "Overdue": 1,
            "Efficiency" : "95.1%"},
        {"Month" : "2024-08",
            "Completed" : 59,
            "Pending" : 8,
            "Overdue": 2,
            "Efficiency" : "90.4%"},
        {"Month" : "2024-09",
            "Completed" : 64,
            "Pending" : 4,
            "Overdue": 0,
            "Efficiency" : "97.2%"}]

def energy_consumption():
    return [{"Month": "2024-01", 
            "Electricity" :45600 ,
            "Water" : 12800,
            "Gas" : 8900,
            "Cost" : 185200,},
        {"Month" : "2024-02",
            "Electricity": 44200 ,
            "Water" : 12200,
            "Gas" : 8600,
            "Cost" : 178900,},
        {"Month": "2024-03",
            "Electricity" : 46800,
            "Water" : 13200,
            "Gas" : 9200,
            "Cost" : 192400,},
        {"Month": "2024-04",
            "Electricity" : 48200,
            "Water" : 13600,
            "Gas" : 9500,
            "Cost" : 198600,},         
        {"Month": "2024-05",
            "Electricity" : 49800,
            "Water" : 14100,
            "Gas" : 9800,
            "Cost" : 205200,},
        {"Month": "2024-06", 
            "Electricity" : 52200,
            "Water" : 14800,
            "Gas" : 10200,
            "Cost" : 215400, },
        {"Month": "2024-07",
            "Electricity" : 54600,
            "Water" : 15200,
            "Gas" : 10600,
            "Cost" : 225800,    },
        {"Month": "2024-08",
            "Electricity" : 53200,
            "Water" : 14900,
            "Gas" : 10400,
            "Cost" : 219600,},
        {"Month": "2024-09",
            "Electricity" : 51800,
            "Water" : 14600,
            "Gas" : 10100,
            "Cost" : 212800,}]

def tenant_satisfaction():
    return[{"Month" :0,
         "Score": 4.2},
        {"Month" :1,
         "Score": 4.5},
        {"Month" :2,
         "Score": 4.7},
        {"Month" :3,
         "Score": 3.8},
        {"Month" :4,
         "Score": 4.1}]
        
def tenant_retention():
    return[{"Year" : 2020,
        "Rate": 68},
        {"Year" : 2021,
        "Rate": 72},
        {"Year" : 2022,
        "Rate": 76},
        {"Year" : 2023,
        "Rate": 78},
        {"Year" : 2024,
        "Rate": 82}]
        
def daily_visitor_trends():
    return [{"Date": "2024-09-10",
         "Visitors" : 142,
         "Entry" : 186,
         "Exit" : 178},
        {"Date": "2024-09-11",
            "Visitors" : 158,
            "Entry" : 205,
            "Exit" : 192},
        {"Date": "2024-09-12",
            "Visitors" : 134,
            "Entry" : 175,
            "Exit" : 168},
        {"Date": "2024-09-13",
            "Visitors" : 167,
            "Entry" : 48,
            "Exit" : 209},
        {"Date": "2024-09-14",
            "Visitors" : 189,
            "Entry" : 245,
            "Exit" : 238},
        {"Date": "2024-09-15",
            "Visitors" : 203,
            "Entry" : 267,
            "Exit" : 251},
        {"Date": "2024-09-16",
            "Visitors" : 178,
            "Entry" : 234,
            "Exit" : 225}]
    
def hourly_access_pattern():
    return [{"Hour": "6:00",
         "Entry": 12,
         "Exit": 8},
        {"Hour": "7:00",
        "Entry": 28,
        "Exit": 15},
        {"Hour": "8:00",
        "Entry": 45,
        "Exit": 22},
        {"Hour": "9:00",
        "Entry": 67,
        "Exit": 18},
        {"Hour": "10:00",
        "Entry": 89,
        "Exit": 25},
        {"Hour": "11:00",
        "Entry": 78,
        "Exit": 35},
        {"Hour": "12:00",
        "Entry": 65,
        "Exit": 42},
        {"Hour": "13:00",
        "Entry": 58,
        "Exit": 38},
        {"Hour": "14:00",
        "Entry": 64,
        "Exit": 45},
        {"Hour": "15:00",
        "Entry": 71,
        "Exit": 48},
        {"Hour": "16:00",
        "Entry": 83,
        "Exit": 62},
        {"Hour": "17:00",
        "Entry": 45,
        "Exit": 78},
        {"Hour": "18:00",
        "Entry": 72,
        "Exit": 95},
        {"Hour": "19:00",
        "Entry": 45,
        "Exit": 82},
        {"Hour": "20:00",
        "Entry": 28,
        "Exit": 65},
        {"Hour": "21:00",
        "Entry": 18,
        "Exit": 45}]
    
def portfolio_heatmap():
    return[{"Floor": "Ground",
            "Block": "A",
            "Occupancy": "95%"},
           {"Floor": "Ground",
            "Block": "B",
            "Occupancy": "88%"},
           {"Floor": "1st",
            "Block": "A",
            "Occupancy": "92%"},
           {"Floor": "1st",
            "Block": "B",
            "Occupancy": "85%"},
           {"Floor": "2nd",
            "Block": "A",
            "Occupancy": "78%"},
           {"Floor": "2nd",
            "Block": "B",
            "Occupancy": "82%"},
           {"Floor": "3rd",
            "Block": "A",
            "Occupancy": "76%"},
           {"Floor": "3rd",
            "Block": "B",
            "Occupancy": "79%"}]

def performance_summary():
    return{"Total Properties": "3 Sites",
        "Total Spaces": "597 Units",
        "Average Occupancy": "83.4%",
        "Monthly Revenue": "$714.8K",
        "Collection Revenue": "96.8%"}