# app/constants/mobile_app_status_code.py

class AppStatusCode:
    # Authentication
    AUTHENTICATION_CREDENTIALS_INVALID = "101"
    AUTHENTICATION_IS_FIRSTAUTHENTICATION_ATTEMPT = "102"
    AUTHENTICATION_USERPROFILE_LOCKED = "103"
    AUTHENTICATION_PASSWORD_EXPIRED = "104"
    AUTHENTICATION_USER_INVALID = "105"
    AUTHENTICATION_USER_INACTIVE = "106"
    AUTHENTICATION_USERNAME_INVALID = "107"
    AUTHENTICATION_SUCCESS = "108"
    AUTHENTICATION_LOGOUT = "109"
    AUTHENTICATION_TOKEN_INVALID = "110"
    AUTHENTICATION_SESSION_TIMEOUT = "111"
    AUTHENTICATION_USER_ACCOUNT_DELETED = "112"
    AUTHENTICATION_UNAUTHORIZED_ACCESS = "113"
    AUTHENTICATION_VERSION_UNMATCHED = "114"
    AUTHENTICATION_NEW_VERSION_AVAILABLE = "115"
    AUTHENTICATION_LICENSE_EXPIRY = "116"
    AUTHENTICATION_NEW_MASTERDATA_AVAILABLE = "117"
    RESTRICTUSER_LOGIN_FROM_DEVICE = "118"
    AUTHENTICATION_INVALID_PIN = "119"
    AUTHENTICATION_ROLE_CHANGE = "120"
    AUTHENTICATION_ADUSER_PASSWORDCANNOTCHANGE = "121"
    AUTHENTICATION_USER_OTP_REQUIRED = "122"
    AUTHENTICATION_USER_OTP_EXPIRED = "123"
    AUTHENTICATION_USER_OTP_INCORRECT = "124"
    AUTHENTICATION_PIN_EXISTS = "125"
    AUTHENTICATION_TOKENVERIFICATION_LIMIT_EXCEEDED = "126"
    AUTHENTICATION_PIN_SEQUENTIAL_OR_REPEATED = "127"

    # Common
    OPERATION_FAILED = "0"
    DATA_RETRIEVED_SUCCESSFULLY = "1"
    RECORD_SAVED_SUCCESSFULLY = "2"
    RECORD_DELETED_SUCCESSFULLY = "3"
    INCORRECT_JSON_DATA = "4"
    INVALID_HEADER_DATETIME = "10"
    INVALID_INPUT = "11"
    INVALID_TIMESTAMP = "201"

    # Email
    EMAIL_SENT_FAIL = "300"
    EMAIL_SENT_SUCCESS = "301"
    NO_OF_EMAIL_ALLOWED = "302"

    # User
    USER_USERNAME_IS_UNIQUE = "701"
    USER_USERNAME_IS_VALID = "702"
    USER_USERNAME_IS_NOTREGISTERED = "703"
    USER_ID_IS_INVALID = "710"
    USER_DATA_RETRIEVE_TYPE_INVALID = "711"

    # Organisation
    ORGANISATION_NAME_INVALID = "1005"
    ORGANISATION_NAME_VALID = "1006"

    # V3 App Services
    STATUS_SUCCESS = "100"
    OPERATION_ERROR = "12"
    INVALID_DEALSTAGE_ACCESS = "509"
    INVALID_DEALHISTORY_ACCESS = "510"
    INVALID_ACTIVITY_STAGE_ACCESS = "411"
    ACTIVITY_ALREADY_EXIST_FOR_SAME_DATETIME = "412"
    EDIT_NOT_ALLOWED = "413"
    RETURN_DEAL_NOT_ALLOWED = "414"
    DUPLICATE_DEAL_ADD_WARNING = "415"
    DUPLICATE_DEAL_ADD_ERROR = "416"
    USER_ON_LEAVE = "417"
    INVALID_ATTACHMENT_FORMAT = "418"
    UNAUTHORIZED_ACTION = "901"
    REQUEST_IS_APPROVED_OR_REJECTED = "902"
    REQUEST_IS_EXISTS = "903"
