FROM python:3.12-slim AS builder

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Create venv
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#  Runner stage 
FROM python:3.12-slim

WORKDIR /app

# Install runtime libs
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy venv
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
ENV PYTHONPATH=/app

# Copy shared code
COPY shared/ shared/

# Copy facility service code
COPY facility_service/ facility_service/

# fix for not running  Copy auth_service so imports work
COPY auth_service/ auth_service/

#entry point
CMD ["uvicorn", "facility_service.app.main:app", "--host", "0.0.0.0", "--port", "8002", "--root-path", "/facility"]
#